### ISSUE TITLE
None of the buttons on the compass work

### ISSUE THREAD

**Issue by isabel-anastasiadis** [DreadLord369/PlanetNavigationTools#6]
Hullo,

I've just installed the mod and built myself a compass.  When I bring it up, it looks like you should be able to click the little square buttons on the compass to add new locations etc., but none of them does anything.

Here is my log file:
[starbound.log](https://github.com/DreadLord369/PlanetNavigationTools/files/7772025/starbound.log)

The mods I have installed are:
- Stackable, Non-Perishable Food
- Race Traits
- Planet Navigation Tools

Let me know if you need any more info.

Thanks,
Isabel

**Comment by isabel-anastasiadis** [comment]
Oh yeah, my Build Id for Starbound is 4369387, in case that's helpful too.

**Comment by DreadLord369** [comment]
Thanks for raising this. At first glance it seems like an adjustment I needed to make to get the minimap fully functional has affected the compass and surface mapper.

I will do some testing and push out an update when done.

**Comment by DreadLord369** [comment]
I've found the issue and have a fix.

I should be able to push the update later today.

**Comment by isabel-anastasiadis** [comment]
Great thanks so much!

**Comment by DreadLord369** [comment]
This has been addresses in #7 
This release has been published to Steam.
Closing Issue
